/**
 * Page copy (everything that isn't shared content). Voice: short declaratives, no exclamation marks,
 * and only what the product does today. Arabic mirrors this shape in ../ar/pages.ts.
 */
export const PAGES = {
  home: {
    heroSub: "Run the whole agency in one place — from brief to client sign‑off.",
    thread: {
      marker: "Out of the thread",
      title: "Your agency runs on WhatsApp. It shouldn’t",
      lead: "The work gets done. The operation is invisible. Operra is where the agency actually runs.",
      caption: "How common agency moments move from the chat into Operra",
      colThread: "The thread",
      colOperra: "In Operra",
    },
    workflow: {
      marker: "How work moves",
      title: "From client brief to approved delivery, on one path",
      lead: "Every job follows the same chain. Step through it — each step is a real screen from the product.",
      job: "One job, in motion",
      jobLabel: "A job at the approval stage",
    },
    proof: {
      marker: "Why it holds",
      title: "Built for how agencies actually work",
      lead: "Generic tools make you bend them into shape. Operra already knows clients, projects, stages and sign‑off.",
      teamSends: "Your team sends it",
      clientDecides: "Your client decides",
    },
    themes: {
      marker: "Built around agency work",
      title: "Less chasing, more visibility",
      lead: "Operra is opinionated about what agencies lose time on: repeating workflows, knowing who owns what, and seeing trouble early.",
      all: "All features",
    },
    roles: {
      marker: "Every seat in the agency",
      title: "One workspace, the right view for each person",
      lead: "Three roles, enforced by one permission system. Clients never see anything internal.",
      more: "What each role can do",
    },
    brand: {
      marker: "Your workspace",
      title: "Your name on it, your data kept apart",
      lead: "Every agency gets its own workspace with its own logo and colours, on its own address. Clients sign in to your brand — in Arabic or English.",
    },
    solutions: {
      marker: "Solutions",
      title: "Starts with workflows agencies already run",
      lead: "Every workspace comes with starter modules you can edit or replace.",
      see: "See the workflow",
    },
  },
  product: {
    metaTitle: "Product overview",
    metaDescription:
      "How Operra is structured: clients, projects, reusable modules and tasks; a role for everyone from founders to clients; and a branded workspace for every agency.",
    marker: "Product overview",
    title: "One system of record for the work itself",
    lead: "Generic tools know what a task is. Operra knows clients, projects, stages and sign‑off — so the agency stops bending tools into shape and drifting back to the thread.",
    model: {
      marker: "The model",
      title: "Everything hangs off the client",
      lead: "Five levels, each with one job. Every client works the same way, so anyone can find their way around any project.",
      label: "Operra’s structure, from agency to task",
      nodes: [
        { label: "Agency", note: "Your workspace: team, brand, templates." },
        { label: "Clients", note: "Contacts, internal notes, team, portal logins." },
        { label: "Projects", note: "Dates, status, owner, team. Progress from tasks." },
        { label: "Modules", note: "Reusable workflows: stages and fields." },
        { label: "Tasks", note: "One per stage to start. Assigned, dated, discussed." },
      ],
      caption:
        "A Content module on a project. Each stage is a task; the current stage is highlighted, and the dot marks the stage that goes to the client for approval.",
    },
    roles: {
      marker: "Roles",
      title: "Every seat in the agency, one permission system",
      lead: "Three roles — Admin, Team member and Client — enforced on the server. Buttons someone can’t use don’t appear, and clients never see anything internal.",
    },
    mobile: {
      marker: "On any screen",
      title: "The same workspace on your phone",
      lead: "A bottom navigation bar on small screens, so approvals, status changes and chat don’t wait for a laptop.",
    },
    setup: {
      marker: "Getting started",
      title: "Your own workspace in a few minutes",
      lead: "Sign up, brand it, invite your people. Each workspace keeps its data apart from every other agency’s.",
      steps: [
        { title: "Create your workspace", body: "Name your agency and choose its address. It’s set up with an admin account and the starter module templates." },
        { title: "Make it yours", body: "Upload your logo and pick your colours, with a live preview. Your own domain can follow." },
        { title: "Invite your team and clients", body: "Invite people by email with a role. Each one gets a short guided tour for that role." },
        { title: "Tune your workflows", body: "Adjust the starter module templates so stages and fields match how you work." },
      ],
      more: "See every feature",
    },
  },
  features: {
    metaTitle: "Features",
    metaDescription:
      "Reusable workflows, client approvals, a client portal, project and team chat, role dashboards, a project health matrix and white-label branding — every Operra feature, shown in the real product.",
    marker: "Features",
    title: "What Operra does, shown in the product",
    lead: "No roadmap promises. Every screen on this page is the product as it works today.",
    jump: "Feature sections",
    platformMarker: "Platform",
    platformTitle: "The foundations under every workspace",
    faqMarker: "Questions",
    faqTitle: "Details people ask about",
  },
  solutions: {
    metaTitle: "Solutions by agency type",
    metaDescription:
      "How content and social agencies, production studios, performance marketing teams and full-service agencies run their work in Operra.",
    marker: "Solutions",
    title: "Built for the way your kind of agency works",
    lead: "Every workspace starts with module templates for common agency disciplines. Use them as they are, edit them, or build your own.",
    moduleSuffix: "module",
    howItRuns: "How it runs",
    detail: {
      metaTitle: "Operra for {name}",
      breadcrumb: "Solutions",
      seeDemo: "See the demo",
      moduleMarker: "Starter module",
      moduleTitle: "The {module} workflow",
      moduleLead:
        "Included in every workspace. Add it to a project and Operra creates one task per stage; approval stages go to the client automatically.",
      fields: "Fields on the module",
      fieldsNote: "Rename stages, add fields or build new modules in Module Templates.",
      practiceMarker: "In practice",
      practiceTitle: "How it runs day to day",
      others: "Other agency types",
    },
  },
  pricing: {
    metaTitle: "Pricing",
    metaDescription: "One Operra plan with every feature included: a branded workspace for your agency. Start with a free trial.",
    marker: "Pricing",
    title: "One plan, everything included",
    trial: "Free trial",
    free: "Free",
    trialDays: "{days} days, then choose to continue.",
    trialNoDays: "Try it with your own team and clients.",
    trialPoints: ["Your own branded workspace", "Every feature switched on", "No card needed to start"],
    perAgency: "Priced per agency",
    perAgencyNote: "Based on the size of your team. Tell us about your agency and we’ll send a quote.",
    talk: "Talk to us",
    faqMarker: "Questions",
    faqTitle: "Pricing and setup, answered",
  },
  demo: {
    metaTitle: "Interactive demo",
    metaDescription:
      "Walk through Operra step by step — client, project, module, task, review, approval, delivery — then step inside the demo agency as an admin, team member or client.",
    marker: "Interactive demo",
    title: "Walk through a real project",
    lead: "Follow one job at a sample agency, Northwind Studio, from the client’s profile to approved delivery. Use the steps or your arrow keys.",
    tourTitle: "Workflow tour",
    liveMarker: "Live demo",
    liveTitle: "Now try it yourself",
    previewLead:
      "Step inside the demo agency as an admin, a team member or a client. No account needed — it’s the real product with sample data, and it’s read-only, so click anything.",
    previewCta: "Explore the demo workspace",
    previewNote: "Nothing you do there is saved.",
    accountsLead: "The demo workspace is a real Operra deployment with sample data. Sign in with any account — each role sees a different workspace.",
    accountsNote: "It’s shared with other visitors, so don’t enter anything private.",
    signIns: "Demo sign-ins",
    passwordAll: "Password (all)",
    roles: ["Admin", "Team member", "Client"],
    viewsMarker: "Three roles",
    viewsTitle: "One workspace, a different view for each role",
    ctaTitle: "See it with your own clients",
  },
  about: {
    metaTitle: "About",
    metaDescription: "Why Operra exists, what the name means, and the principles behind the operating system for agencies.",
    marker: "About Operra",
    title: "Agencies don’t lack tools. They lack a system of record for the work",
    lead: "Most agencies run the business through a chat group per client, a sheet per retainer and a shared drive nobody trusts. The work gets done; the operation is invisible. Operra is the place the agency actually runs.",
    nameMarker: "The name",
    nameTitle: "The body of work, operated",
    personalityMarker: "Personality",
    personalityTitle: "The calm person in the control room",
    personalityLead: "Knows where everything is, never raises their voice, makes the hard thing look simple.",
    is: "Operra is",
    never: "…but never",
    personality: [
      ["Precise", "Cold"],
      ["Confident", "Loud"],
      ["Fast", "Rushed"],
      ["Premium", "Exclusive"],
      ["Simple", "Simplistic"],
      ["Operational", "Bureaucratic"],
      ["Locally fluent", "Localised as an afterthought"],
    ] as [string, string][],
    principlesMarker: "Principles",
    principlesTitle: "What we hold ourselves to",
    principles: [
      { title: "Built from agency work", body: "Operra started as the internal system of a working agency. Its stages, approvals and dashboards come from running real client projects." },
      { title: "Your brand leads", body: "Clients sign in to your agency, not to us. The workspace carries your name, logo and colours." },
      { title: "Your data stays apart", body: "Every query is scoped to your workspace, and isolation between agencies is tested automatically." },
      { title: "Arabic is written, not translated", body: "Arabic and English are both first-class, with a native right-to-left layout and emails in each person’s language." },
      { title: "Only what ships", body: "Everything on this site is in the product today. Screenshots come from the real app with sample data." },
      { title: "Numbers over adjectives", body: "“3 approvals waiting” beats “streamlined approvals”. Short sentences, no exclamation marks." },
    ],
  },
  contact: {
    metaTitle: "Contact",
    metaDescription: "Talk to the Operra team about pricing, a walkthrough, or your existing workspace.",
    marker: "Contact",
    title: "Talk to us",
    lead: "Pricing, a walkthrough for your team, or help with your workspace. Send a message and we’ll reply by email.",
    email: "Email",
    lookingTitle: "Looking around first",
    lookingBefore: "The",
    lookingLink: "interactive demo",
    lookingAfter: "walks through a real project, and you can step inside the demo agency as an admin, team member or client.",
    alreadyTitle: "Already on Operra",
    alreadyBefore: "Your workspace has a built-in guide under Help. Your admin can reset passwords in Team & Users. To sign in, go to",
    alreadyLink: "your workspace",
  },
  login: {
    metaTitle: "Log in",
    metaDescription: "Sign in to your agency’s Operra workspace.",
    title: "Log in to your workspace",
    appLead: "Sign in with your email and password. We’ll take you straight to your agency’s workspace.",
    appCta: "Continue to sign in",
    ownDomain: "Your agency on its own domain",
    lead: "Every agency has its own Operra workspace at its own address. Enter yours and we’ll take you to its sign-in page.",
    unknownTitle: "Don’t know your address",
    unknownBody: "Ask your agency’s admin, or look for your invitation email. Clients use the same address as their agency’s team.",
    forgotTitle: "Forgot your password",
    forgotBody: "Your workspace admin can set a new one in Team & Users.",
    noneTitle: "No workspace yet",
    noneStart: "Start a free trial",
    or: "or",
    noneDemo: "explore the demo",
  },
  start: {
    metaTitle: "Start free trial",
    metaDescription: "Create your agency’s own Operra workspace: branded, with every feature included.",
    marker: "Start free trial",
    title: "Get your agency’s own workspace",
    selfServeLead: "Create it yourself in a few minutes. Every feature is on from the start.",
    selfServeCta: "Create your workspace",
    selfServeAlt: "Prefer a walkthrough first?",
    requestLead: "Tell us about your agency and we’ll set up a dedicated workspace for it.",
    nextTitle: "What happens next",
    selfServeSteps: [
      { title: "Create your account", body: "Your name, email and a password." },
      { title: "Name your agency", body: "Choose its address — this is where your team and clients sign in." },
      { title: "Add your brand", body: "Logo and colours, with a live preview of your workspace." },
      { title: "Your workspace is ready", body: "Set up in seconds, with starter templates and a guided tour. Then invite your team." },
    ],
    requestSteps: [
      { title: "You tell us about your agency", body: "Two minutes, on this page." },
      { title: "We set up your workspace", body: "A dedicated workspace, ready for your team." },
      { title: "You get the admin sign-in", body: "By email, with your workspace address." },
      { title: "Brand it, invite your team", body: "Name, logo and colours in Settings → Brand, then your team and clients." },
    ],
    included: ["Every feature, no tiers", "Arabic and English", "Client portal and approvals", "Your data kept apart"],
  },
  notFound: {
    marker: "404 — Not found",
    title: "This page doesn’t exist",
    body: "Looking for your agency’s workspace? Log in to get there.",
    home: "Back to home",
  },
};

export type Pages = typeof PAGES;
