/** Interface strings used by components (header, footer, forms, tour). Page copy lives in pages.ts. */
export const UI = {
  skip: "Skip to content",
  home: "Operra home",
  mainNav: "Main",
  mobileNav: "Mobile",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  logIn: "Log in",
  startTrial: "Start free trial",
  openDemo: "Open the live demo",
  exploreProduct: "Explore the product",
  newTab: "(opens in a new tab)",
  language: "Language",
  /** Shown on the switcher: the name of the *other* language, in that language. */
  otherLanguage: "العربية",
  otherLanguageCode: "ar",
  footerNote: "Product screenshots show the demo workspace with sample data",
  cta: {
    title: "Run the whole agency in one place",
    lead: "Start a free trial with your own branded workspace, or step inside the demo agency first.",
  },
  role: "Role",
  workflowStages: "Workflow stages",
  clientApproval: "(client approval)",
  schematic: { live: " (in progress)", done: " (done)", next: " (next)" },
  tour: {
    label: "Operra workflow",
    step: "Step",
    previous: "Previous step",
    next: "Next:",
    startOver: "Start over",
  },
  form: {
    optional: "(optional)",
    select: "Select…",
    sending: "Sending…",
    alsoEmail: "You can also email",
    honeypot: "Company URL",
    checkFields: "Please check the highlighted fields.",
    sendFailed: "We couldn’t send this right now. Please try again in a moment.",
    required: "{label} is required.",
    invalidEmail: "Enter a valid email address.",
    chooseRole: "Choose your role.",
    chooseTeamSize: "Choose your team size.",
    chooseLanguage: "Choose a language.",
    chooseTopic: "Choose a topic.",
    name: "Your name",
    workEmail: "Work email",
    email: "Email",
    agencyName: "Agency name",
    agency: "Agency",
    website: "Agency website",
    yourRole: "Your role",
    teamSize: "Team size",
    agencyType: "What you do",
    workspaceLanguage: "Workspace language",
    notes: "Anything we should know?",
    notesPlaceholder: "How you run projects today, tools you’re replacing, timing…",
    topic: "Topic",
    message: "Message",
    requestWorkspace: "Request my workspace",
    privacy: "We only use these details to set up your workspace and reply to you.",
    sendMessage: "Send message",
    trialDoneTitle: "Request received",
    trialDoneBody:
      "We’ll set up your workspace and reply by email with its address and your admin sign-in. Until then, the demo agency is open.",
    contactDoneTitle: "Message sent",
    contactDoneBody: "We’ll reply to the email address you gave us.",
  },
  /** Select options: `value` is what we store (English), `label` is shown. */
  options: {
    roles: [
      { value: "Founder / managing director", label: "Founder / managing director" },
      { value: "Head of ops / account director", label: "Head of ops / account director" },
      { value: "Account manager, producer, designer or media buyer", label: "Account manager, producer, designer or media buyer" },
      { value: "Other", label: "Other" },
    ],
    teamSize: [
      { value: "1-5", label: "1–5" },
      { value: "6-15", label: "6–15" },
      { value: "16-50", label: "16–50" },
      { value: "51+", label: "51+" },
    ],
    agencyType: [
      { value: "Content & social", label: "Content & social" },
      { value: "Production", label: "Production" },
      { value: "Performance & paid media", label: "Performance & paid media" },
      { value: "Full-service", label: "Full-service" },
      { value: "Other", label: "Other" },
    ],
    language: [
      { value: "English", label: "English" },
      { value: "Arabic", label: "Arabic" },
      { value: "Both", label: "Both" },
    ],
    topic: [
      { value: "Sales", label: "Sales" },
      { value: "Demo", label: "Demo" },
      { value: "Existing workspace", label: "Existing workspace" },
      { value: "Other", label: "Other" },
    ],
  },
  workspace: {
    label: "Workspace address",
    continue: "Continue",
    invalid: "Enter your workspace address, for example app.youragency.com",
    help: "It’s in your welcome email, and usually on your agency’s own domain.",
  },
};

export type Ui = typeof UI;
export type Option = { value: string; label: string };
