import {
  pgTable,
  pgEnum,
  text,
  uuid,
  timestamp,
  boolean,
  integer,
  jsonb,
  date,
  primaryKey,
  index,
  uniqueIndex,
  customType,
  pgSequence,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { DEFAULT_TRIAL_DAYS } from "../lib/billing/defaults";

const bytea = customType<{ data: Buffer; driverData: Buffer }>({ dataType: () => "bytea" });

/* ------------------------------------------------------------------ */
/* Enums                                                               */
/* ------------------------------------------------------------------ */

export const roleEnum = pgEnum("role", ["admin", "employee", "client"]);

export const taskStatusEnum = pgEnum("task_status", [
  "todo",
  "in_progress",
  "review",
  "waiting_client",
  "completed",
]);

export const priorityEnum = pgEnum("priority", ["low", "medium", "high", "urgent"]);

export const projectStatusEnum = pgEnum("project_status", [
  "planning",
  "active",
  "on_hold",
  "completed",
  "cancelled",
]);

export const approvalStatusEnum = pgEnum("approval_status", [
  "none",
  "pending",
  "approved",
  "rejected",
]);

export const chatChannelEnum = pgEnum("chat_channel", ["internal", "client"]);

/** Lifecycle of a tenant (agency workspace). */
export const tenantStatusEnum = pgEnum("tenant_status", ["provisioning", "active", "suspended", "cancelled"]);

export const subscriptionStatusEnum = pgEnum("subscription_status", [
  "trialing",
  "active",
  "past_due",
  "canceled",
  "incomplete",
  "unpaid",
  /** The free trial ended without a subscription (set on expiry; access is also computed live). */
  "expired",
]);

export const provisionStatusEnum = pgEnum("provision_status", ["pending", "running", "completed", "failed"]);

export const onboardingStatusEnum = pgEnum("onboarding_status", ["active", "completed", "skipped"]);

/* ------------------------------------------------------------------ */
/* Shared JSON types                                                   */
/* ------------------------------------------------------------------ */

export type WorkflowStage = {
  name: string;
  /** Stage that requires a client decision (approve / reject). */
  clientApproval?: boolean;
};

export type ModuleField = {
  key: string;
  label: string;
  type: "text" | "number" | "date" | "url" | "select" | "textarea";
  options?: string[];
};

/* ------------------------------------------------------------------ */
/* Tenancy + users                                                     */
/* ------------------------------------------------------------------ */

/** Server-side source of instance serials: OPR-000001, OPR-000002, … */
export const orgSerialSeq = pgSequence("org_serial_seq", { startWith: 1, increment: 1 });

export const organizations = pgTable("organizations", {
  id: uuid("id").primaryKey().defaultRandom(),
  /** Permanent, unique instance identifier generated by the database (never by a client). */
  serial: text("serial")
    .notNull()
    .unique()
    .default(sql`'OPR-' || lpad(nextval('org_serial_seq')::text, 6, '0')`),
  status: tenantStatusEnum("status").notNull().default("active"),
  /** The shared preview tenant. Demo tenants are read-only for visitors and never hold customer data. */
  isDemo: boolean("is_demo").notNull().default(false),
  /** Optional custom domain (e.g. app.acme.com) resolved to this tenant. */
  customDomain: text("custom_domain").unique(),
  /** Set when the first admin finished (or skipped) the workspace tutorial. */
  onboardedAt: timestamp("onboarded_at", { withTimezone: true }),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  /** Brand name (English / Latin). */
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  /* ---- White-label brand settings (edited on Settings → Brand) ---- */
  nameAr: text("name_ar"),
  /** Logo as a data: URL (PNG, JPG, WebP or SVG, kept small). */
  logo: text("logo"),
  primaryColor: text("primary_color").notNull().default("#0a0a0a"),
  accentColor: text("accent_color").notNull().default("#e8dcc8"),
  defaultLang: text("default_lang").notNull().default("ar"),
  showLanding: boolean("show_landing").notNull().default(true),
  contactEmail: text("contact_email"),
  whatsapp: text("whatsapp"),
  instagram: text("instagram"),
  xHandle: text("x_handle"),
  linkedin: text("linkedin"),
  /** Client names shown on the landing page ("Trusted by"). */
  showcaseClients: jsonb("showcase_clients").$type<string[]>().notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * A person: one sign-in (email + password) and one verified-email status, across every agency they
 * belong to. Their place in each agency is a membership row in `users`.
 */
export const accounts = pgTable("accounts", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  loginCount: integer("login_count").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Single-use email-verification links (token stored hashed). */
export const emailVerifications = pgTable(
  "email_verifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    /** The address being verified; the link only counts while the account still has this email. */
    email: text("email").notNull(),
    tokenHash: text("token_hash").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("email_verifications_account_idx").on(t.accountId)],
);

/** Single-use password-reset links (token stored hashed, 1 hour). */
export const passwordResets = pgTable(
  "password_resets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("password_resets_account_idx").on(t.accountId)],
);

/**
 * A membership: one person (`accounts`) in one agency (`organizations`), with their role there.
 * The table keeps its historical name; every session and every tenant-scoped query works on a
 * membership, so a person in two agencies has two rows and never sees across them.
 */
export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    /** Copy of the account's email, kept in sync (used for display and notification emails). */
    email: text("email").notNull(),
    role: roleEnum("role").notNull().default("employee"),
    title: text("title"),
    /** Set only for client-role users: which client company they belong to. */
    clientId: uuid("client_id").references(() => clients.id, { onDelete: "set null" }),
    active: boolean("active").notNull().default(true),
    /** Language used for this user's emails (kept in sync with the AR | EN switch). */
    lang: text("lang").notNull().default("ar"),
    /** Send notifications by email as well as in the app. */
    emailNotifications: boolean("email_notifications").notNull().default(true),
    /** Team members only: which onboarding track fits their work ("account" or "production"). */
    focus: text("focus"),
    /** Last time the user opened the team chat (drives the unread badge). */
    teamChatSeenAt: timestamp("team_chat_seen_at", { withTimezone: true }),
    /** Last request from a session of this membership (updated at most every few minutes). */
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("users_org_account_idx").on(t.orgId, t.accountId),
    uniqueIndex("users_org_email_idx").on(t.orgId, t.email),
    index("users_org_idx").on(t.orgId),
    index("users_account_idx").on(t.accountId),
  ],
);

export const sessions = pgTable(
  "sessions",
  {
    id: text("id").primaryKey(), // sha256 of the cookie token
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    /** Preview sessions into the demo tenant: every write is refused server-side. */
    readOnly: boolean("read_only").notNull().default(false),
  },
  // Signing someone out everywhere (suspension, password change, deactivation) goes by user.
  (t) => [index("sessions_user_idx").on(t.userId)],
);

/* ------------------------------------------------------------------ */
/* Clients                                                             */
/* ------------------------------------------------------------------ */

export const clients = pgTable(
  "clients",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    industry: text("industry"),
    contactName: text("contact_name"),
    contactEmail: text("contact_email"),
    phone: text("phone"),
    website: text("website"),
    notes: text("notes"),
    active: boolean("active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("clients_org_idx").on(t.orgId)],
);

/** Internal team members assigned to a client account. */
export const clientTeam = pgTable(
  "client_team",
  {
    clientId: uuid("client_id")
      .notNull()
      .references(() => clients.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.clientId, t.userId] })],
);

/* ------------------------------------------------------------------ */
/* Projects + modules                                                  */
/* ------------------------------------------------------------------ */

export const projects = pgTable(
  "projects",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    clientId: uuid("client_id")
      .notNull()
      .references(() => clients.id, { onDelete: "restrict" }),
    name: text("name").notNull(),
    description: text("description"),
    status: projectStatusEnum("status").notNull().default("planning"),
    startDate: date("start_date"),
    endDate: date("end_date"),
    ownerId: uuid("owner_id").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("projects_org_idx").on(t.orgId), index("projects_client_idx").on(t.clientId)],
);

/** Internal users with access to a project (admins always have access). */
export const projectMembers = pgTable(
  "project_members",
  {
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
  },
  // By member too: an employee's project visibility is "projects I'm a member of".
  (t) => [primaryKey({ columns: [t.projectId, t.userId] }), index("project_members_user_idx").on(t.userId)],
);

/** Reusable module definition (Content, Production, ...). */
export const moduleTemplates = pgTable(
  "module_templates",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description"),
    color: text("color").notNull().default("slate"),
    stages: jsonb("stages").$type<WorkflowStage[]>().notNull(),
    fields: jsonb("fields").$type<ModuleField[]>().notNull().default([]),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("module_templates_org_idx").on(t.orgId)],
);

/** A module instance attached to a project. Stages/fields are snapshotted from the template. */
export const projectModules = pgTable(
  "project_modules",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    templateId: uuid("template_id").references(() => moduleTemplates.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    color: text("color").notNull().default("slate"),
    stages: jsonb("stages").$type<WorkflowStage[]>().notNull(),
    fields: jsonb("fields").$type<ModuleField[]>().notNull().default([]),
    fieldValues: jsonb("field_values").$type<Record<string, string>>().notNull().default({}),
    position: integer("position").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("project_modules_project_idx").on(t.projectId)],
);

/* ------------------------------------------------------------------ */
/* Tasks                                                               */
/* ------------------------------------------------------------------ */

export const tasks = pgTable(
  "tasks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    moduleId: uuid("module_id").references(() => projectModules.id, { onDelete: "set null" }),
    /** Workflow stage within the module (e.g. "Writing"). */
    stage: text("stage"),
    title: text("title").notNull(),
    description: text("description"),
    assigneeId: uuid("assignee_id").references(() => users.id, { onDelete: "set null" }),
    status: taskStatusEnum("status").notNull().default("todo"),
    priority: priorityEnum("priority").notNull().default("medium"),
    dueDate: date("due_date"),
    /** Visible to client users on the portal (deliverables, approvals). */
    clientVisible: boolean("client_visible").notNull().default(false),
    requiresApproval: boolean("requires_approval").notNull().default(false),
    approvalStatus: approvalStatusEnum("approval_status").notNull().default("none"),
    createdById: uuid("created_by_id").references(() => users.id, { onDelete: "set null" }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("tasks_org_idx").on(t.orgId),
    index("tasks_project_idx").on(t.projectId),
    index("tasks_assignee_idx").on(t.assigneeId),
  ],
);

export const taskComments = pgTable(
  "task_comments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    taskId: uuid("task_id")
      .notNull()
      .references(() => tasks.id, { onDelete: "cascade" }),
    authorId: uuid("author_id").references(() => users.id, { onDelete: "set null" }),
    body: text("body").notNull(),
    /** Internal notes are never shown to client users. */
    internal: boolean("internal").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("task_comments_task_idx").on(t.taskId)],
);

export const attachments = pgTable(
  "attachments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    taskId: uuid("task_id")
      .notNull()
      .references(() => tasks.id, { onDelete: "cascade" }),
    uploaderId: uuid("uploader_id").references(() => users.id, { onDelete: "set null" }),
    fileName: text("file_name").notNull(),
    storageKey: text("storage_key").notNull(),
    mimeType: text("mime_type").notNull(),
    size: integer("size").notNull(),
    /** Deliverable shared with the client. */
    clientVisible: boolean("client_visible").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("attachments_task_idx").on(t.taskId)],
);

/** Project requests submitted from the public landing page. */
export const leads = pgTable(
  "leads",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    company: text("company"),
    email: text("email"),
    phone: text("phone"),
    service: text("service"),
    message: text("message"),
    lang: text("lang").notNull().default("ar"),
    status: text("status").notNull().default("new"), // new | contacted | won | lost
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("leads_org_idx").on(t.orgId, t.createdAt)],
);

/** File contents, used for uploads when no external file store is configured. */
export const fileBlobs = pgTable("file_blobs", {
  key: text("key").primaryKey(),
  data: bytea("data").notNull(),
});

/* ------------------------------------------------------------------ */
/* Collaboration                                                       */
/* ------------------------------------------------------------------ */

export const chatMessages = pgTable(
  "chat_messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    authorId: uuid("author_id").references(() => users.id, { onDelete: "set null" }),
    channel: chatChannelEnum("channel").notNull().default("internal"),
    body: text("body").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("chat_messages_project_idx").on(t.projectId, t.channel)],
);

/** Org-wide chat for agency staff (admins + employees). */
export const teamMessages = pgTable(
  "team_messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    authorId: uuid("author_id").references(() => users.id, { onDelete: "set null" }),
    body: text("body").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("team_messages_org_idx").on(t.orgId, t.createdAt)],
);

export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    actorId: uuid("actor_id").references(() => users.id, { onDelete: "set null" }),
    type: text("type").notNull(), // assigned | mention | comment | status | approval | chat
    title: text("title").notNull(),
    /** Arabic version of the title (the English one is in `title`). */
    titleAr: text("title_ar"),
    /** Optional excerpt, e.g. the comment or message that triggered it. */
    body: text("body"),
    link: text("link"),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("notifications_user_idx").on(t.userId, t.readAt)],
);

export const activityLog = pgTable(
  "activity_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    actorId: uuid("actor_id").references(() => users.id, { onDelete: "set null" }),
    projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }),
    taskId: uuid("task_id").references(() => tasks.id, { onDelete: "cascade" }),
    action: text("action").notNull(), // task.created, task.status, comment.added, ...
    summary: text("summary").notNull(),
    /** Whether this entry may be shown to the client on their portal. */
    clientVisible: boolean("client_visible").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("activity_org_idx").on(t.orgId, t.createdAt),
    index("activity_project_idx").on(t.projectId),
    index("activity_task_idx").on(t.taskId),
  ],
);

/* ------------------------------------------------------------------ */
/* SaaS platform: plans, subscriptions, signup, provisioning           */
/* ------------------------------------------------------------------ */

export const plans = pgTable("plans", {
  code: text("code").primaryKey(),
  name: text("name").notNull(),
  /** Display price in minor units; null = priced on request. The payment provider holds the real price. */
  priceCents: integer("price_cents"),
  currency: text("currency").notNull().default("USD"),
  interval: text("interval").notNull().default("month"),
  trialDays: integer("trial_days").notNull().default(DEFAULT_TRIAL_DAYS),
  /** The payment provider's price for this plan (e.g. a Stripe Price ID). Falls back to STRIPE_PRICE_<CODE>. */
  stripePriceId: text("stripe_price_id"),
  active: boolean("active").notNull().default(true),
  sort: integer("sort").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** One subscription per tenant; the payment provider is the source of truth, mirrored by webhooks. */
export const subscriptions = pgTable(
  "subscriptions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .unique()
      .references(() => organizations.id, { onDelete: "cascade" }),
    planCode: text("plan_code")
      .notNull()
      .references(() => plans.code),
    status: subscriptionStatusEnum("status").notNull().default("trialing"),
    trialEndsAt: timestamp("trial_ends_at", { withTimezone: true }),
    currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }),
    cancelAtPeriodEnd: boolean("cancel_at_period_end").notNull().default(false),
    /** "none" (trial only), "stripe", or "test" (development only). */
    provider: text("provider").notNull().default("none"),
    providerCustomerId: text("provider_customer_id"),
    providerSubscriptionId: text("provider_subscription_id").unique(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("subscriptions_status_idx").on(t.status)],
);

/** Every webhook/billing event processed once (idempotency + audit trail). */
export const billingEvents = pgTable(
  "billing_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    provider: text("provider").notNull(),
    eventId: text("event_id").notNull(),
    type: text("type").notNull(),
    orgId: uuid("org_id").references(() => organizations.id, { onDelete: "set null" }),
    payload: jsonb("payload").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("billing_events_provider_event_idx").on(t.provider, t.eventId)],
);

/** A new customer's signup, kept server-side until the workspace is provisioned. */
export const signups = pgTable(
  "signups",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tokenHash: text("token_hash").notNull().unique(),
    email: text("email").notNull(),
    name: text("name").notNull(),
    passwordHash: text("password_hash").notNull(),
    lang: text("lang").notNull().default("en"),
    planCode: text("plan_code")
      .notNull()
      .references(() => plans.code),
    companyName: text("company_name"),
    companyNameAr: text("company_name_ar"),
    slug: text("slug"),
    logo: text("logo"),
    primaryColor: text("primary_color"),
    accentColor: text("accent_color"),
    defaultLang: text("default_lang"),
    /** "trial" or "subscribe" — chosen on the last step. */
    startMode: text("start_mode"),
    /** Last completed wizard step (0 account … 3 plan). */
    step: integer("step").notNull().default(0),
    orgId: uuid("org_id").references(() => organizations.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    /** Anonymous visitor id (links the sign-up to site visits) and country, for the funnel. */
    visitorId: text("visitor_id"),
    country: text("country"),
  },
  (t) => [index("signups_email_idx").on(t.email), index("signups_created_idx").on(t.createdAt)],
);

/**
 * First-party product analytics for the Operra control center: site visits, sign-up steps,
 * sign-ins and daily activity. No raw IPs; visitors are a random id in a first-party cookie.
 */
export const platformEvents = pgTable(
  "platform_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    type: text("type").notNull(),
    visitorId: text("visitor_id"),
    accountId: uuid("account_id").references(() => accounts.id, { onDelete: "cascade" }),
    orgId: uuid("org_id").references(() => organizations.id, { onDelete: "cascade" }),
    signupId: uuid("signup_id").references(() => signups.id, { onDelete: "set null" }),
    path: text("path"),
    country: text("country"),
    meta: jsonb("meta").$type<Record<string, string | number>>(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("platform_events_type_idx").on(t.type, t.createdAt),
    index("platform_events_visitor_idx").on(t.visitorId),
    index("platform_events_account_idx").on(t.accountId, t.createdAt),
  ],
);

/** Provisioning record per signup. Unique on signup, so retries never create a second tenant. */
export const provisionings = pgTable("provisionings", {
  id: uuid("id").primaryKey().defaultRandom(),
  signupId: uuid("signup_id")
    .notNull()
    .unique()
    .references(() => signups.id, { onDelete: "cascade" }),
  orgId: uuid("org_id")
    .unique()
    .references(() => organizations.id, { onDelete: "cascade" }),
  status: provisionStatusEnum("status").notNull().default("pending"),
  step: text("step"),
  error: text("error"),
  attempts: integer("attempts").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
});

/** Email invitations to join a tenant. The token is stored hashed. */
export const invitations = pgTable(
  "invitations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    role: roleEnum("role").notNull().default("employee"),
    focus: text("focus"),
    title: text("title"),
    clientId: uuid("client_id").references(() => clients.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull().unique(),
    invitedById: uuid("invited_by_id").references(() => users.id, { onDelete: "set null" }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    /** Set when the invitation was actually delivered by email: accepting it then proves the address. */
    emailedAt: timestamp("emailed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("invitations_org_idx").on(t.orgId, t.email)],
);

/** Tutorial progress per user (role-specific flows). */
export const userOnboarding = pgTable("user_onboarding", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id, { onDelete: "cascade" }),
  flow: text("flow").notNull(),
  step: integer("step").notNull().default(0),
  status: onboardingStatusEnum("status").notNull().default("active"),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
});

/** Single-use tokens that carry a signed-in session to another host (tenant subdomain / custom domain). */
export const loginTokens = pgTable("login_tokens", {
  tokenHash: text("token_hash").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  usedAt: timestamp("used_at", { withTimezone: true }),
});

/** Fixed-window rate limiting shared by all instances. */
export const rateLimits = pgTable("rate_limits", {
  key: text("key").primaryKey(),
  count: integer("count").notNull().default(0),
  windowStart: timestamp("window_start", { withTimezone: true }).notNull().defaultNow(),
});

/* ------------------------------------------------------------------ */
/* Operra staff (platform control center) — separate from tenant users */
/* ------------------------------------------------------------------ */

export const platformAdmins = pgTable("platform_admins", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  passwordHash: text("password_hash").notNull(),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const platformSessions = pgTable("platform_sessions", {
  id: text("id").primaryKey(), // sha256 of the cookie token
  adminId: uuid("admin_id")
    .notNull()
    .references(() => platformAdmins.id, { onDelete: "cascade" }),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
});

export type Organization = typeof organizations.$inferSelect;
export type Subscription = typeof subscriptions.$inferSelect;
export type Plan = typeof plans.$inferSelect;
export type Signup = typeof signups.$inferSelect;

export type User = typeof users.$inferSelect;
export type Account = typeof accounts.$inferSelect;
export type Role = (typeof roleEnum.enumValues)[number];
export type TaskStatus = (typeof taskStatusEnum.enumValues)[number];
export type Priority = (typeof priorityEnum.enumValues)[number];
export type ProjectStatus = (typeof projectStatusEnum.enumValues)[number];
export type Task = typeof tasks.$inferSelect;
export type Project = typeof projects.$inferSelect;
export type Client = typeof clients.$inferSelect;
export type ProjectModule = typeof projectModules.$inferSelect;
export type ModuleTemplate = typeof moduleTemplates.$inferSelect;
