import type { Ui } from "../en/ui";
import { UI as EN } from "../en/ui";

/** Option `value`s stay English (they're what we store and email); only labels are Arabic. */
const labels = (list: { value: string }[], ar: string[]) => list.map((o, i) => ({ value: o.value, label: ar[i] }));

export const UI: Ui = {
  skip: "انتقل إلى المحتوى",
  home: "الصفحة الرئيسية لأوبيرّا",
  mainNav: "الرئيسية",
  mobileNav: "قائمة الجوال",
  openMenu: "فتح القائمة",
  closeMenu: "إغلاق القائمة",
  logIn: "تسجيل الدخول",
  startTrial: "ابدأ التجربة المجانية",
  openDemo: "افتح العرض الحي",
  exploreProduct: "استكشف المنتج",
  newTab: "(يفتح في نافذة جديدة)",
  language: "اللغة",
  otherLanguage: "English",
  otherLanguageCode: "en",
  footerNote: "صور المنتج من مساحة العمل التجريبية ببيانات نموذجية",
  cta: {
    title: "أدِر وكالتك كلها من مكان واحد",
    lead: "ابدأ تجربة مجانية بمساحة عمل تحمل هويتك، أو ادخل إلى الوكالة التجريبية أولاً.",
  },
  role: "الدور",
  workflowStages: "مراحل سير العمل",
  clientApproval: "(موافقة العميل)",
  schematic: { live: " (قيد التنفيذ)", done: " (تم)", next: " (التالي)" },
  tour: {
    label: "سير العمل في أوبيرّا",
    step: "الخطوة",
    previous: "الخطوة السابقة",
    next: "التالي:",
    startOver: "من البداية",
  },
  form: {
    optional: "(اختياري)",
    select: "اختر…",
    sending: "جارٍ الإرسال…",
    alsoEmail: "ويمكنك أيضاً مراسلتنا على",
    honeypot: "رابط الشركة",
    checkFields: "راجع الحقول المحدّدة من فضلك.",
    sendFailed: "تعذّر الإرسال الآن. حاول مرة أخرى بعد قليل.",
    required: "حقل «{label}» مطلوب.",
    invalidEmail: "أدخل بريداً إلكترونياً صحيحاً.",
    chooseRole: "اختر دورك.",
    chooseTeamSize: "اختر حجم فريقك.",
    chooseLanguage: "اختر اللغة.",
    chooseTopic: "اختر الموضوع.",
    name: "اسمك",
    workEmail: "بريد العمل",
    email: "البريد الإلكتروني",
    agencyName: "اسم الوكالة",
    agency: "الوكالة",
    website: "موقع الوكالة",
    yourRole: "دورك",
    teamSize: "حجم الفريق",
    agencyType: "مجال عملكم",
    workspaceLanguage: "لغة مساحة العمل",
    notes: "هل هناك ما يجب أن نعرفه؟",
    notesPlaceholder: "كيف تديرون المشاريع اليوم، الأدوات التي تستبدلونها، التوقيت…",
    topic: "الموضوع",
    message: "الرسالة",
    requestWorkspace: "اطلب مساحة عملي",
    privacy: "نستخدم هذه البيانات فقط لإعداد مساحة عملك والرد عليك.",
    sendMessage: "إرسال الرسالة",
    trialDoneTitle: "وصلنا طلبك",
    trialDoneBody: "سنجهّز مساحة عملك ونرد عليك بالبريد بعنوانها وبيانات دخول المدير. وحتى ذلك الحين، الوكالة التجريبية متاحة لك.",
    contactDoneTitle: "أُرسلت الرسالة",
    contactDoneBody: "سنرد على البريد الذي أدخلته.",
  },
  options: {
    roles: labels(EN.options.roles, [
      "مؤسس / مدير عام",
      "مدير عمليات / مدير حسابات",
      "مدير حساب أو منتج أو مصمم أو مشتري إعلانات",
      "أخرى",
    ]),
    teamSize: labels(EN.options.teamSize, ["1–5", "6–15", "16–50", "+51"]),
    agencyType: labels(EN.options.agencyType, ["المحتوى والسوشال ميديا", "الإنتاج", "التسويق بالأداء والإعلانات", "خدمات شاملة", "أخرى"]),
    language: labels(EN.options.language, ["الإنجليزية", "العربية", "الاثنتان"]),
    topic: labels(EN.options.topic, ["المبيعات", "عرض توضيحي", "مساحة عمل قائمة", "أخرى"]),
  },
  workspace: {
    label: "عنوان مساحة العمل",
    continue: "متابعة",
    invalid: "أدخل عنوان مساحة عملك، مثل app.youragency.com",
    help: "تجده في رسالة الترحيب، وغالباً يكون على نطاق وكالتك.",
  },
};
